import { QSystem } from "../../Engine/System";
import { ProjectOptions, Project } from "./Project";
import { ProjectTemplate } from "./ProjectTemplate";
export declare class ProjectSystem extends QSystem {
    private project;
    PreInit(): void;
    Init(): void;
    PostInit(): void;
    BeginPlay(): void;
    OnPreview(): void;
    LaunchPorject(port: number): void;
    LaunchPor(portUseable: boolean, port: number): void;
    Shutdown(): void;
    Tick(DeltaTime: number): void;
    GetProjectTemplates(): ProjectTemplate[];
    CreateProject(parameter: ProjectOptions): void;
    private recordProject;
    OpenProject(file: string): void;
    CheckPathAndName(dir: string, name: string): boolean;
    RunProject(file: string): void;
    GetCurrentProject(): Project;
    GetProjectFile(): string;
    GetProjectDir(): string;
    GetContentDir(): string;
    GetConfigDir(): string;
    GetSavedDir(): string;
    GetScenesDir(): string;
    GetSettingDir(): string;
    GetResourceReferenceDir(): string;
    GetDigitalTwinsDir(): string;
    GetPrefabObjectDir(): string;
    GetScriptDir(): string;
    GetThumbnailDir(): string;
    GetUserSettingsDir(): string;
    GetProjectExtension(): string;
    GetSceneFilename(SceneName: any): string;
    GetSettingFilename(name: any): string;
    GetDigitalTwinFilename(Name: any): string;
    GetPrefabObjectFilename(Name: any): string;
    GetSettingExtension(): string;
    GetSceneExtension(): string;
    GetDigitalTwinExtension(): string;
    GetPrefabObjectExtension(): string;
    private GetProjectTemplateDir;
    GetUnrealProjectDir(): string;
}
